// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-EacI0E7jYkjfgCM9VdjpBYeA7EJO9A',
    appId: '1:988600219687:web:1ade24732799b3afbcb602',
    messagingSenderId: '988600219687',
    projectId: 'fir-flutter-codelab-46118',
    authDomain: 'fir-flutter-codelab-46118.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-46118.appspot.com',
    measurementId: 'G-2MLNHL5C33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wxCCakzEpZJ35ygkN4Cv2PBREA87fio',
    appId: '1:988600219687:android:8ba5650bdccc7b9cbcb602',
    messagingSenderId: '988600219687',
    projectId: 'fir-flutter-codelab-46118',
    storageBucket: 'fir-flutter-codelab-46118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArnMFX8P6h76_7N5Bd9l6Lmufxkmsk-XA',
    appId: '1:988600219687:ios:73daba9affb422e7bcb602',
    messagingSenderId: '988600219687',
    projectId: 'fir-flutter-codelab-46118',
    storageBucket: 'fir-flutter-codelab-46118.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArnMFX8P6h76_7N5Bd9l6Lmufxkmsk-XA',
    appId: '1:988600219687:ios:73daba9affb422e7bcb602',
    messagingSenderId: '988600219687',
    projectId: 'fir-flutter-codelab-46118',
    storageBucket: 'fir-flutter-codelab-46118.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
